apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dokuwiki
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '11.1.5'  # Ersetzen Sie dies durch die gewünschte Version von DokuWiki
    chart: dokuwiki
    helm:
      values: |
        dokuwikiUsername: 'admin'
        dokuwikiPassword: 'adminpassword'  # Setzen Sie hier ein sicheres Passwort
        dokuwikiEmail: 'user@example.com'
        service:
          type: LoadBalancer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dokuwiki  # Erstellen Sie ggf. diesen Namespace oder verwenden Sie einen vorhandenen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
