apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.13.0
    helm:
      values: |
        pushgateway:
          enabled: false
        alertmanager:
          service:
            type: ClusterIP
        server:
          service:
            type: ClusterIP
        nodeExporter:
          enabled: true
          hostNetwork: false
          hostPID: false
          service:
            type: ClusterIP
            port: 9100
            targetPort: 9100
          hostPort: 0
          extraArgs:
            - --no-collector.wifi
            - --no-collector.hwmon
          volumes: []
          volumeMounts: []
        kubeStateMetrics:
          enabled: true
          hostNetwork: false
        prometheusOperator:
          hostNetwork: false
        prometheus:
          prometheusSpec:
            hostNetwork: false
            containers:
              - name: prometheus
                volumeMounts: []
            volumes: []
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
